version: "3.7"

services:
  frontend:
    build: ./frontend
    image: nuxt_dev
    container_name: nuxt_dev
    volumes:
      - ./frontend:/app
      - app_node_modules:/app/node_modules
      - app_dotnuxt:/app/.nuxt
    # command: npm run dev
    command: [yarn, dev]
    ports:
      - "3000:3000"
    networks:
      - front-network

  fastapi:
    build: ./rest_api
    container_name: fastapi
    restart: always
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION_MINUTES=125
      - DB_ENDPOINT=postgres:5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=test_db
      - REDIS_IP=redis
      - REDIS_PORT=6379
    ports:
      - 8000:8000
    networks:
      - front-network
    # volumes:
    #  - ./rest_api:/app
    command: "python3 -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
  
  postgres:
    image: postgres:14.1-alpine
    container_name: postgresql_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    ports:
      - 5432:5432
    networks:
      - front-network
    volumes: 
      - db:/var/lib/postgresql/data
      - postgres-content:/home/postgres/
  
  pgadmin:
    # connect to postgres using "postgres", NOT "localhost" or "127.0.0.1"
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    depends_on:
      - postgres
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - front-network
    restart: unless-stopped

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - front-network

networks:
  front-network:
    driver: bridge
volumes:
  pgadmin:
  db:
  postgres-content:
  app_node_modules:
  app_dotnuxt:
